//
//  NCSFieldConstants.h
//  NCSNavField
//
//  Created by Jacob Van Order on 2/20/13.
//  Copyright (c) 2013 Northwestern University. All rights reserved.
//

#import <Foundation/Foundation.h>

FOUNDATION_EXPORT NSString * ENDPOINT_IMAGE_DOWNLOADED;

FOUNDATION_EXPORT NSString * SettingsDidChangeNotification;
FOUNDATION_EXPORT NSString * CLIENT_ID;
FOUNDATION_EXPORT NSString * CORE_URL;
FOUNDATION_EXPORT NSString * CAS_SERVER_URL;
FOUNDATION_EXPORT NSString * PGT_RECEIVE_URL;
FOUNDATION_EXPORT NSString * PGT_RETRIEVE_URL;
FOUNDATION_EXPORT NSString * PURGE_FIELDWORK_BUTTON;
FOUNDATION_EXPORT NSString * UPCOMING_DAYS_TO_SYNC;
FOUNDATION_EXPORT NSString * PAST_DAYS_TO_SYNC;

FOUNDATION_EXPORT NSString * HAS_MIGRATED_TO_AUTO_LOCATION;
